deploy-job:
  docker:
   - image: circleci/node:10
  steps:
   - run:
       name: Deploy Master to Firebase
       command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting

workflows:
  version: 2

  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master