version: 2.1
description: Deploy to Firebase Hosting
commands:
  deploy:
    description: Deploy to firebase
    steps:
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Gulp
          command: gulp
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive