
version: 2.1

executors:
  my-executor:
    docker:
      - image: ubuntu:16.04

workflows:
  socotra:
    jobs:
      - deploy:
          name: deploy-firebase-hosting
          filters:
            branches:
              only: release

jobs:
  deploy:
    executor: my-executor
    parameters:
      firebase-username:
        type: string
      password:
        type: string


    steps:
      - checkout
            - run:
                  name: Install Dependencies
                  command: npm install
            - run:
                  name: Run Gulp
                  command: gulp
            - run:
                  name: Firebase Deploy
                  command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
            

