version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:10

workflows:
  socotra:
    jobs:
      # Load config from develop into Socotra sandbox
      - load-config:
          name: deploy-to-firebase
          filters:
            branches:
              only: master

jobs:
  load-config:
    executor: my-executor

    steps:
      - run:
       name: Deploy Master to Firebase
       command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting